#!/bin/bash
set -euo pipefail

COMPARTMENT=""
CMPID=""

# Usage function
function usage() {
  echo "Usage: $0 --compartment <compartment-name> [--debug]"
  echo ""
  echo "Options:"
  echo "  --compartment   Name of the compartment (required)"
  echo "  --debug         Enable debug mode (optional)"
  echo "  --help|-h      Show this help message"
  exit 1
}   

# Get the direcory of the current script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/oci-functions.sh"

while [[ $# -gt 0 ]]; do
  case $1 in
    --compartment)
      COMPARTMENT="$2"
      shift # past argument
      shift # past value
      ;;
    --debug)
      set -x
      shift # past argument
      ;;
    --help|-h)
      usage
      ;;
    *) 
      echo "Unknown option: $1"
      usage
      ;;      
  esac
done

# compartment required for this script
if [ -z "$COMPARTMENT" ]; then
   echo "Compartment is required"
   usage
fi

CMPID=$(get_compartment_id "$COMPARTMENT")
if [ -z "$CMPID" ]; then
   echo "Compartment $COMPARTMENT not found"
   exit 1
fi

oci logging log-group list --compartment-id "$CMPID" --all | jq -r '.data[] | [."display-name", .id] | @tsv' | column -t