#!/usr/bin/env bash

set -euo pipefail

COMPARTMENT=""
CMPID=""
UTILIZATION=false

function usage() {
  echo "Usage: $0 [--compartment <compartment-name>] [--debug]"
  echo ""
  echo "Options:"
  echo "  --compartment   Name of the compartment (optional, lists all compartments if not provided)"
  echo "  --debug         Enable debug mode (optional)"
  echo "  --help|-h      Show this help message"
  exit 1
}

function list_subnet() {
  local compartment_id="$1"

  json=$(oci network subnet list --compartment-id "$compartment_id")
  cmp_name=$(oci iam compartment get --compartment-id "$compartment_id" | jq -r '.data.name')

  if [ "$json" != "" ]; then
    echo "$json" | jq --arg cmpname $cmp_name -r '.data[] | [$cmpname, ."display-name", .id] | @tsv' | column -t
  else
    echo "No subnets found in compartment $cmp_name"
  fi
  if [ "$UTILIZATION" = true ]; then
     echo "$json" | jq -r '.data[]' | while read subnet; do
       subnet_id=$(echo "$subnet" | jq -r '.id')
       subnet_name=$(echo "$subnet" | jq -r '."display-name"')
       get_utilization "$subnet_id" "$subnet_name"
     done
   fi


}

function get_utilization() {
    echo -e "$2 Utilization: \n $(oci network ipam get-subnet-cidr-utilization --subnet-id $1 | jq -r '.data."ip-inventory-cidr-utilization-summary"[] | [."address-type",.utilization] | @tsv' | column -t)"
} 

# Get the direcory of the current script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/oci-functions.sh"

while [[ $# -gt 0 ]]; do
  case $1 in
    --compartment)
      COMPARTMENT="$2"
      shift # past argument
      shift # past value
      ;;
    --debug)
      set -x
      shift # past argument
      ;;
    --utilization|--util)
      UTILIZATION=true
      shift # past argument
      ;;
    --help|-h)
      usage
      ;;
    *) 
      echo "Unknown option: $1"
      usage
      ;;      
  esac
done


if [ -n "$COMPARTMENT" ]; then
  CMPID=$(get_compartment_id "$COMPARTMENT")
  if [ -z "$CMPID" ]; then
    echo "Compartment $COMPARTMENT not found"
    usage
  fi
  list_subnet "$CMPID"

else

  for cmp in $(oci iam compartment list --compartment-id-in-subtree true --all | jq -r '.data[] | .id'); do
    list_subnet "$cmp"
  done
fi

