#!/usr/bin/env bash

set -euo pipefail

COMPARTMENT=""
CMPID=""

function usage() {
  echo "Usage: $0 [--compartment <compartment-name>] [--debug]"
  echo ""
  echo "Options:"
  echo "  --compartment   Name of the compartment (optional, lists all compartments if not provided)"
  echo "  --debug         Enable debug mode (optional)"
  echo "  --help|-h      Show this help message"
  exit 1
}

# Get the direcory of the current script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. "$SCRIPT_DIR/oci-functions.sh"

while [[ $# -gt 0 ]]; do
  case $1 in
    --compartment)
      COMPARTMENT="$2"
      shift # past argument
      shift # past value
      ;;
    --debug)
      set -x
      shift # past argument
      ;;
    --help|-h)
      usage
      ;;
    *) 
      echo "Unknown option: $1"
      usage
      ;;      
  esac
done


if [ -n "$COMPARTMENT" ]; then
  CMPID=$(get_compartment_id "$COMPARTMENT")
  if [ -z "$CMPID" ]; then
    echo "Compartment $COMPARTMENT not found"
    usage
  fi
  json=$(oci network subnet list --compartment-id "$CMPID")
  if [ "$json" != "" ]; then
    echo "$json" | jq --arg cmpname $COMPARTMENT -r '.data[] | [$cmpname, ."display-name", .id] | @tsv' | column -t
  else
    echo "No subnets found in compartment $COMPARTMENT"
  fi
  exit 0
else

  for cmp in $(oci iam compartment list --compartment-id-in-subtree true --all | jq -r '.data[] | .id'); do
    json=$(oci network subnet list --compartment-id "$cmp")
    cmp_name=$(oci iam compartment get --compartment-id "$cmp" | jq -r '.data.name')
    if [ "$json" != "" ]; then
      echo "$json" | jq --arg cmpname $cmp_name -r '.data[] | [$cmpname, ."display-name", .id] | @tsv' | column -t
    fi
  done
fi