#!/usr/bin/env bash
set -euo pipefail

COMPARTMENT=""
CMPID=""
CLUSTER=""
CLUSTERID=""
KUBECONFIG_FILE="$HOME/.kube/config"
OVERWRITE="false"
ALIAS=""
DEBUG="false"

function usage() {
  echo "Usage: $0 --compartment <compartment-name> --cluster <cluster-name> [--debug] [--file <kubeconfig-file>] [--overwrite] [--alias <context-alias>]"
  echo ""
  echo "Options:"
  echo "  --compartment   Name of the compartment (required)"
  echo "  --cluster       Name of the cluster (required)"
  echo "  --file          Output kubeconfig to specified file. Defaults to $HOME/.kube/config (optional)"
  echo "  --overwrite     Overwrite existing kubeconfig file (optional)"
  echo "  --alias         Change context name to <alias> (optional)"
  echo "  --debug         Enable debug mode (optional)"
  echo "  --help|-h       Show this help message"
  exit 1
}

# Get the directory of the current script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/oci-functions.sh"

while [[ $# -gt 0 ]]; do
  case $1 in
    --compartment)
      COMPARTMENT="$2"
      shift # past argument
      shift # past value
      ;;
    --cluster)
      CLUSTER="$2"
      shift # past argument
      shift # past value
      ;;
    --file)
      KUBECONFIG_FILE="$2"
      shift # past argument
      shift # past value
      ;;
    --overwrite)
      OVERWRITE="true"
      shift # past argument
      ;;
    --alias)
      ALIAS="$2"
      shift # past argument
      shift # past value
      ;;
    --debug)
      DEBUG="true"
      set -x
      shift # past argument
      ;;
    --help|-h)
      usage
      ;;
    *) 
      echo "Unknown option: $1"
      usage
      ;;
  esac
done

TMPFILE="$(mktemp)"

CMPID=$(get_compartment_id "$COMPARTMENT")
if [ -z "$CMPID" ]; then
  echo "Compartment $COMPARTMENT not found"
  usage
fi

CLUSTERID=$(get_cluster_id "$CMPID" "$CLUSTER")
if [ -z "$CLUSTERID" ]; then
  echo "Cluster $CLUSTER not found in compartment $COMPARTMENT"
  usage
fi

oci ce cluster create-kubeconfig --cluster-id "$CLUSTERID" --file -  --kube-endpoint PRIVATE_ENDPOINT > "$TMPFILE"

CONTEXT=$(cat "$TMPFILE" | grep 'current-context:' | awk '{print $2}')

export KUBECONFIG_FILE=${KUBECONFIG_FILE:-$HOME/.kube/config}

kubectl config delete-context "$ALIAS" 2>/dev/null || true

#default KUBECONFIG_FILE to $HOME/.kube/config
if [ -f "$KUBECONFIG_FILE" ] && [ "$OVERWRITE" != "true" ]; then
  echo "Kubeconfig file $KUBECONFIG_FILE already exists. Use --overwrite to overwrite."
  echo "Merging new kubeconfig into existing file." 
  export KUBECONFIG=$(realpath "$KUBECONFIG_FILE"):$TMPFILE
  kubectl config view --merge --flatten > "$TMPFILE.merged"
  if [ "$DEBUG" != "true" ]; then
    mv "$TMPFILE.merged" "$KUBECONFIG_FILE"
    rm "$TMPFILE"
  else
    cp "$TMPFILE.merged" "$KUBECONFIG_FILE"
  fi
else
  mv "$TMPFILE" "$KUBECONFIG_FILE"
fi

if [ -n "$ALIAS" ]; then
  kubectl config rename-context "$CONTEXT" "$ALIAS"
fi