#!/usr/bin/env bash
set -euo pipefail

COMPARTMENT=""
CMPID=""
CLUSTER=""
CLUSTERID=""
KUBECONFIG_FILE="$HOME/.kube/config"
OVERWRITE="false"
ALIAS=""
DEBUG="false"

function usage() {
  echo "Usage: $0 --compartment <compartment-name> --cluster <cluster-name> [--debug] [--file <kubeconfig-file>] [--overwrite] [--alias <context-alias>]"
  echo ""
  echo "Options:"
  echo "  --compartment   Name of the compartment (optinal)"
  echo "  --debug         Enable debug mode (optional)"
  echo "  --help|-h       Show this help message"
  exit 1
}

# Get the directory of the current script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/oci-functions.sh"

while [[ $# -gt 0 ]]; do
  case $1 in
    --compartment)
      COMPARTMENT="$2"
      shift # past argument
      shift # past value
      ;;
    --debug)
      DEBUG="true"
      set -x
      shift # past argument
      ;;
    --help|-h)
      usage
      ;;
    *) 
      echo "Unknown option: $1"
      usage
      ;;
  esac
done


printf "Gathering policy counts for compartments...\n\n"

declare -A cmp_policy_count

declare -A cmp_policy_parent
cmp_id_list=$(oci iam compartment list --include-root --compartment-id-in-subtree true --all | jq -r '.data[] | .id')


for cmp in $cmp_id_list; do
    cmp_policy_count[$cmp]=$(oci iam policy list --compartment-id=$cmp | jq -r '.data[].statements[]' | wc -l)
    cmp_policy_parent[$cmp]=$(oci iam compartment get --compartment-id=$cmp | jq -r '.data."compartment-id" // "none"')
done;

policytable='Compartment\tPolicy-Count\tPolicy-Chain-Total\n'

for cmp in $cmp_id_list; do
    
    parentid=${cmp_policy_parent[$cmp]}
    totalcount=${cmp_policy_count[$cmp]}
    cmpname=$(get_compartment_name "$cmp")
    prefix=""
    while [ "$parentid" != "none" ]; do
        prefix+="-"
        totalcount=$((totalcount + ${cmp_policy_count[$parentid]}))
        parentid=${cmp_policy_parent[$parentid]}
    done

    policytable+="${prefix}${cmpname}\t${cmp_policy_count[$cmp]}\t${totalcount}\n"
    totalcount=0
    prefix=""
done

printf "Policy Counts by Compartment:\n\n"
echo -e "$policytable" | column -t 
